import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { serverSideTranslations} from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'

export default function Home() {
  const { t, i18n } = useTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{t("common:hello")}</h1>
      </main>

      
    </div>
  )
}

export const getStaticProps = async ({ locale}) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common','home'])),
  },
})
